language: rust

rust:
  # Test only on nightly as we use the specialization feature
  - nightly

jobs:
  include:
    - name: Clippy
      script:
        - rustup component add clippy || travis_terminate 0
        - cargo +$TRAVIS_RUST_VERSION clippy -- -D clippy::all

    - name: Test
      before_script: bash .travis/scripts/generate_readme.sh
      script:
        - cargo test
      deploy:
        provider: script
        script: bash .travis/scripts/cargo_publish.sh $TRAVIS_RUST_VERSION
        on:
          tags: true
          all_branches: true

    - name: Build Manual
      script:
        - cargo install mdbook
        - cd manual && mdbook build
      before_deploy:
        - mkdir -p target/manual/crates/serde-version
        - cp -R manual/book/* target/manual/crates/serde-version
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_PAGES_TOKEN
        local_dir: target/manual
        keep_history: true
        on:
          #tags: true
          all_branches: true

  allow_failures:
    - name: Clippy
    - name: Build Manual
