language: rust

matrix:
  include:
    # Test only on nightly as we use the specialization feature
    - rust: nightly
      script:
        - cargo build
        - cargo test

    - rust: nightly
      name: Clippy
      script:
        - rustup component add clippy || travis_terminate 0
        - cargo clippy -- -D clippy::all

  allow_failures:
    - rust: nightly
      name: Clippy

script:
  - cargo build
